version: '3.9'

services:
  next-app:
    container_name: ava
    platform: linux/amd64
    image: okhubvn/ava:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CMS: ${NEXT_PUBLIC_CMS}
        NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        AUTH_SECRET: ${AUTH_SECRET}
        NEXT_PUBLIC_API_CF7: ${NEXT_PUBLIC_API_CF7}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        AUTH_URL: ${AUTH_URL}
        AUTH_REDIRECT_PROXY_URL: ${AUTH_REDIRECT_PROXY_URL}

    restart: always
    ports:
      - 3000:3000
    networks:
      - ava

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  ava:
    external: true
