import type {Metadata} from 'next'
import '@/styles/globals.css'
import WebVitals from '@/app/_components/web-vitals'
import {gilroy} from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body className={`${gilroy.variable} antialiased`}>
        <WebVitals />
        {children}
      </body>
    </html>
  )
}
